### PR TITLE
Add wake on move features

### PR DESCRIPTION
**Pull request by rickkas7**
New example file, fix hardware SPI for LIS3DH, add wake on move
feature, add rest of configuration constants for LIS3DH.

Also tested the original 2 example files; they still build and work.

### CODE REVIEW

**Comment by ScruffR** [comment]
@monkbroc, please merge and publish ;-)

Although there seems to be a minor problem with the wake logic when the device goes to sleep while the accelerometer is not in "normal" (0g/0g/-1g) position. Subsequent movement doesn't seem to wake my Electron anymore.

There should be a way to trigger wake pin when the delta X/Y/Z exceedes a threshold, not when the absolute values are not 0g/0g/-1g.

**Comment by monkbroc** [comment]
There are a bunch of changes related to pins and SPI. Since you're both confident with those changes I'll merge them in and publish a new version of the asset tracker library.

**Comment by ScruffR** [comment]
@rickkas7, any thoughts on the not-waking-wake in non horizontal/steady position?

**Comment by rickkas7** [comment]
I never was able to figure out how to get gravity compensation to work properly on the LIS3DH, so I just turned off Z-axis sensing instead. That, of course, only works as a workaround when it's laying flat.

**Comment by monkbroc** [comment]
Richard published the new version of this lib. Thanks for the new demo Rick!

**Pull request merged**
